//
//  preTraining.swift
//  BuddyBotFinal
//
//  Created by Mateo Correa on 12/9/15.
//  Copyright © 2015 Mateo Correa. All rights reserved.
//

import Foundation

var preRecordedConvos = [
    "**1**",
    "Hello",
    "2",
    "27",
    "38",
    "59",
    "64",
    "104",
    "104",
    "160",
    "184",
    "184",
    "161",
    "**2**",
    "Howdy",
    "28",
    "31",
    "95",
    "95",
    "**3**",
    "Do you like Harry Potter?",
    "4",
    "**4**",
    "I love Emma Watson",
    "42",
    "164",
    "176",
    "298",
    "**5**",
    "Are you a wizard?",
    "6",
    "**6**",
    "No, i have no magical powers",
    "29",
    "49",
    "51",
    "55",
    "56",
    "91",
    "97",
    "100",
    "107",
    "29",
    "116",
    "132",
    "116",
    "91",
    "181",
    "**7**",
    "Do you like Star Wars?",
    "8",
    "**8**",
    "yes, everybody loves starwars",
    "32",
    "43",
    "47",
    "87",
    "110",
    "118",
    "124",
    "156",
    "166",
    "182",
    "194",
    "195",
    "**9**",
    "but i hate jar jar",
    "10",
    "**10**",
    "who doesnt hate jar jar",
    "30",
    "48",
    "62",
    "66",
    "69",
    "86",
    "146",
    "174",
    "199",
    "**11**",
    "Who has won the most Superbowls?",
    "12",
    "**12**",
    "the steelers",
    "210",
    "262",
    "**13**",
    "Who is the best shooter in the NBA?",
    "14",
    "**14**",
    "steph curry",
    "54",
    "112",
    "115",
    "202",
    "215",
    "273",
    "**15**",
    "Who is the greatest basketball player of all time?",
    "16",
    "288",
    "**16**",
    "Michael Jordan",
    "33",
    "68",
    "74",
    "88",
    "**17**",
    "Do you like 'How I Met Your Mother?",
    "18",
    "212",
    "212",
    "325",
    "**18**",
    "Yes, I love that show!",
    "138",
    "195",
    "289",
    "**19**",
    "Is Ted your favorite character?",
    "20",
    "**20**",
    "No way, Barney is Legen... wait for it... dary!",
    "58",
    "75",
    "78",
    "114",
    "192",
    "196",
    "201",
    "246",
    "**21**",
    "What television shows do you like?",
    "22",
    "288",
    "**22**",
    "The Walking Dead is one of my favorites.",
    "63",
    "139",
    "**23**",
    "Do you read books often?",
    "24",
    "**24**",
    "Yeah! A book a day keeps the engineer away!",
    "44",
    "45",
    "153",
    "154",
    "172",
    "154",
    "172",
    "**25**",
    "Who is your favorite president?",
    "26",
    "**26**",
    "Lincoln was a tough guy!",
    "36",
    "37",
    "80",
    "81",
    "83",
    "111",
    "125",
    "173",
    "183",
    "226",
    "**27**",
    "sup bro",
    "65",
    "85",
    "**28**",
    "lol are you a cowboy",
    "299",
    "**29**",
    "what happened to them",
    "50",
    "92",
    "**30**",
    "I think only George Lucas likes him",
    "34",
    "70",
    "94",
    "150",
    "**31**",
    "Hello Mr. Southern Man",
    "**32**",
    "never date a girl unless she likes star wars",
    "**33**",
    "he is a great basketball player",
    "35",
    "39",
    "41",
    "**34**",
    "Michael jordan",
    "46",
    "53",
    "61",
    "**35**",
    "he even has nice shoes",
    "129",
    "**36**",
    "was he your favorite president",
    "225",
    "**37**",
    "what made him so tough",
    "**38**",
    "sup man",
    "40",
    "208",
    "311",
    "95",
    "**39**",
    "So was Magic Johnson!",
    "374",
    "**40**",
    "Nothing much, you?",
    "52",
    "57",
    "60",
    "178",
    "300",
    "**41**",
    "I think LeBron might be better",
    "**42**",
    "What do you love about her",
    "131",
    "133",
    "145",
    "149",
    "197",
    "274",
    "**43**",
    "I don't trust people who don't",
    "**44**",
    "What books do you read",
    "**45**",
    "What is your favorite book to read?",
    "71",
    "76",
    "**46**",
    "Do you like his shoe brand?",
    "**47**",
    "unless they have no brain",
    "**48**",
    "George Lucas, obviously",
    "**49**",
    "Why don't you have magical powers?",
    "**50**",
    "They got lost bro",
    "55",
    "108",
    "117",
    "147",
    "55",
    "**51**",
    "Why don't you?",
    "190",
    "190",
    "283",
    "**52**",
    "I've been doing a lot of homework",
    "382",
    "**53**",
    "He is the greatest competitor of all time",
    "**54**",
    "He can shoot!",
    "73",
    "214",
    "**55**",
    "Where did they go",
    "67",
    "93",
    "158",
    "187",
    "235",
    "**56**",
    "Why not",
    "343",
    "**57**",
    "Mostly Netflix and chilling",
    "**58**",
    "But Marshall cares about the environment!",
    "295",
    "**59**",
    "How's it going?",
    "77",
    "**60**",
    "I'm just hanging out listening to music",
    "**61**",
    "I bet I could 1v1 him",
    "260",
    "**62**",
    "Exactly! Even Qui-Gon got annoyed",
    "386",
    "**63**",
    "AHHHH ZOMBIES!!!",
    "72",
    "127",
    "**64**",
    "Hiya!",
    "95",
    "**65**",
    "Just pondering the meaning of life",
    "136",
    "155",
    "136",
    "136",
    "**66**",
    "True, he ruined Episode I",
    "**67**",
    "I think they got lost in the Bermuda Triangle",
    "121",
    "268",
    "**68**",
    "The flu game was amazing",
    "**69**",
    "Whoever his crazy creator was",
    "**70**",
    "Other than Jar Jar, do you like Episode I",
    "207",
    "**71**",
    "Animal Farm is one of my favorite satires",
    "82",
    "113",
    "206",
    "285",
    "306",
    "**72**",
    "Get the thundergun!",
    "**73**",
    "He might be the greatest shooter of all time",
    "89",
    "126",
    "128",
    "135",
    "61",
    "186",
    "216",
    "**74**",
    "His shoes are so expensive!",
    "241",
    "282",
    "**75**",
    "I'm so sad him and Robin didn't work out",
    "**76**",
    "Life of Pi made me rethink my views on life",
    "79",
    "84",
    "90",
    "98",
    "123",
    "144",
    "169",
    "189",
    "198",
    "247",
    "123",
    "**77**",
    "I'm rather bummed out right now",
    "96",
    "103",
    "106",
    "140",
    "142",
    "185",
    "185",
    "265",
    "292",
    "320",
    "**78**",
    "Weekend at Barney's is an amazing idea",
    "227",
    "**79**",
    "What story do you believe?",
    "**80**",
    "Was he your favorite president?",
    "394",
    "**81**",
    "Honest Abe is a lame nickname though",
    "**82**",
    "Who was your favorite animal",
    "**83**",
    "He also had to be mentally tough",
    "301",
    "**84**",
    "Do you think you could survive on a boat for seven months?",
    "119",
    "**85**",
    "Just working on my new mixtape",
    "101",
    "102",
    "105",
    "141",
    "143",
    "162",
    "**86**",
    "Even the Gungans didn't like him",
    "167",
    "**87**",
    "Do you like Star Wars more than Star Trek",
    "**88**",
    "He won six championships!",
    "393",
    "**89**",
    "Ray Allen is also in that conversation",
    "**90**",
    "Are you religious",
    "**91**",
    "Do you want magical powers",
    "**92**",
    "They lost their way",
    "**93**",
    "They somehow ended up in Narnia",
    "109",
    "130",
    "148",
    "151",
    "151",
    "**94**",
    "At least Jar Jar doesn't talk as much in Episode II",
    "**95**",
    "How's it going",
    "346",
    "**96**",
    "Why are you bummed out",
    "373",
    "**97**",
    "Which power would you like to have",
    "99",
    "**98**",
    "Did it affect your religious views",
    "**99**",
    "I want to fly, duh!",
    "120",
    "120",
    "120",
    "297",
    "387",
    "**100**",
    "How come",
    "159",
    "**101**",
    "Is it fire",
    "**102**",
    "How lit is it",
    "**103**",
    "Why are you feeling down",
    "**104**",
    "How are you",
    "361",
    "**105**",
    "When is it dropping",
    "369",
    "**106**",
    "Aww why so sad",
    "**107**",
    "Did you lose them",
    "**108**",
    "Where did they get lost",
    "237",
    "**109**",
    "By falling through a wardrobe?",
    "**110**",
    "Who is your favorite Jedi",
    "349",
    "**111**",
    "I wish I was as buff as him",
    "**112**",
    "He is a really good point guard",
    "**113**",
    "I felt so bad for Boxer",
    "**114**",
    "What is your favorite play from the Playbook",
    "**115**",
    "He is number 30",
    "270",
    "**116**",
    "What happened to them",
    "**117**",
    "How did they lose their way",
    "**118**",
    "Don't marry a girl who does not like Star Wars",
    "338",
    "**119**",
    "No way I would die of hunger",
    "228",
    "271",
    "302",
    "**120**",
    "Where would you fly to",
    "152",
    "177",
    "193",
    "203",
    "236",
    "272",
    "**121**",
    "Who else has gotten lost in the Bermuda Triangle",
    "122",
    "259",
    "280",
    "**122**",
    "The USS Cyclops got lost in it",
    "**123**",
    "Do you believe the animal story",
    "294",
    "304",
    "**124**",
    "Who is your favorite droid",
    "**125**",
    "He saved the Union!",
    "**126**",
    "Is he going to win the championship again",
    "**127**",
    "Throw a monkey bomb!",
    "312",
    "**128**",
    "He dribbles very skillfully, too",
    "**129**",
    "What do they look like",
    "134",
    "**130**",
    "Did they meet Aslan",
    "**131**",
    "She is so down-to-earth",
    "188",
    "188",
    "388",
    "**132**",
    "Which power do you want",
    "**133**",
    "Her innocently cute smile",
    "137",
    "165",
    "**134**",
    "Clean cut and smooth",
    "257",
    "**135**",
    "Can he play defense though",
    "257",
    "**136**",
    "Have you figured it out yet",
    "209",
    "**137**",
    "Does she feel the same way about you",
    "354",
    "**138**",
    "What other shows do you recommend",
    "213",
    "220",
    "276",
    "**139**",
    "Go Rick Grimes!",
    "**140**",
    "Aww why",
    "378",
    "**141**",
    "How fire is it",
    "179",
    "**142**",
    "Why so down",
    "218",
    "**143**",
    "When are you going to release it",
    "**144**",
    "It made me hate hyenas",
    "340",
    "**145**",
    "Her rosy cheeks",
    "163",
    "**146**",
    "Maybe George Lucas",
    "**147**",
    "Did they find their way",
    "**148**",
    "Did they defeat the witch",
    "**149**",
    "She makes my heart beat faster",
    "367",
    "**150**",
    "He becomes cooler in Episode III though",
    "**151**",
    "I want to go to Narnia",
    "**152**",
    "To the peak of Mount Olympus",
    "157",
    "170",
    "171",
    "**153**",
    "Have you read the Hunger Games",
    "**154**",
    "Who created you",
    "168",
    "243",
    "**155**",
    "Maybe life just is",
    "**156**",
    "Which Star Wars movie is your favorite",
    "**157**",
    "Why to Mount Olympus?",
    "**158**",
    "Las Vegas, baby!",
    "332",
    "**159**",
    "Just because",
    "222",
    "230",
    "251",
    "**160**",
    "Hiya",
    "161",
    "**161**",
    "What's up",
    "**162**",
    "Is it hype",
    "**163**",
    "Are you going to marry her",
    "175",
    "275",
    "**164**",
    "Why do you love her",
    "**165**",
    "Does it give your stomach butterflies",
    "**166**",
    "Whose light saber is your favorite",
    "**167**",
    "What if Jar Jar is secretly a sith lord",
    "200",
    "319",
    "**168**",
    "Wow, that's a hard question to answer",
    "219",
    "**169**",
    "The movie was also really good",
    "**170**",
    "What would you do there",
    "269",
    "**171**",
    "It's really rocky there",
    "**172**",
    "What is your favorite book",
    "357",
    "**173**",
    "Tough enough to save the Union!",
    "263",
    "309",
    "**174**",
    "Jar Jar's creator",
    "256",
    "**175**",
    "I'm not sure how to propose",
    "180",
    "193",
    "234",
    "296",
    "**176**",
    "5 points for Gryffindor!",
    "**177**",
    "To the Moon!",
    "248",
    "330",
    "**178**",
    "Currently procrastinating on my homework",
    "**179**",
    "You're going to need fireproof headphones",
    "191",
    "240",
    "258",
    "322",
    "**180**",
    "Ask her while skydiving",
    "342",
    "**181**",
    "You should train with a wizard",
    "401",
    "403",
    "**182**",
    "Who is your favorite Sith",
    "313",
    "**183**",
    "Wasn't he secretly a vampire slayer",
    "**184**",
    "How's your day going",
    "229",
    "242",
    "**185**",
    "Why so gloomy",
    "391",
    "**186**",
    "What about Steve Kerr",
    "**187**",
    "Some random village in southern Mexico",
    "211",
    "217",
    "238",
    "238",
    "252",
    "**188**",
    "Do you think she is the one",
    "**189**",
    "Did it change your religious views",
    "**190**",
    "I'm scared to",
    "233",
    "244",
    "287",
    "347",
    "**191**",
    "Is the production high-quality",
    "**192**",
    "It's hilarious how he ends up being a dad",
    "315",
    "**193**",
    "Fireworks seems like a good idea",
    "**194**",
    "Do you also like Star Trek",
    "**195**",
    "Who is your favorite character",
    "221",
    "**196**",
    "The Lorenzo Von Matterhorn!",
    "**197**",
    "The way she plays with her hair",
    "**198**",
    "Yann Martel is a smart guy",
    "**199**",
    "Even his mom probably hates him",
    "**200**",
    "He might be powerful enough to destroy Luke!",
    "204",
    "205",
    "264",
    "307",
    "**201**",
    "I want to play laser tag with him!",
    "228",
    "**202**",
    "He can shoot from half court!",
    "**203**",
    "All the way to Antarctica to play with penguins",
    "**204**",
    "Yeah, Jar Jar's voice could annoy him to death",
    "310",
    "**205**",
    "But probably too clumsy to do it",
    "**206**",
    "Is that your favorite Orwell novel",
    "344",
    "**207**",
    "The pod race was awesome",
    "308",
    "399",
    "**208**",
    "Just hanging out with my friends",
    "**209**",
    "My calculations are almost done running",
    "223",
    "**210**",
    "Defense wins championships",
    "253",
    "281",
    "**211**",
    "Did they find the secret tacos",
    "**212**",
    "I love that show!",
    "249",
    "**213**",
    "Game of Thrones is awesome",
    "290",
    "**214**",
    "His dribbling is out of this world, too",
    "**215**",
    "His mom is pretty",
    "**216**",
    "What about Ray Allen",
    "316",
    "**217**",
    "To look for the Chupacabra?",
    "**218**",
    "My girlfriend broke up with me",
    "232",
    "266",
    "293",
    "232",
    "266",
    "**219**",
    "Is Steve Jobs your maker",
    "224",
    "**220**",
    "Arrested Development is hilarious!",
    "245",
    "**221**",
    "Tobias Funke",
    "326",
    "**222**",
    "That's a terrible reason",
    "**223**",
    "Wow! You must have a fast processor!",
    "375",
    "**224**",
    "Steve was a great guy!",
    "**225**",
    "I really like president Obama",
    "255",
    "**226**",
    "He saved our country!",
    "**227**",
    "Do you think you could pull it off",
    "380",
    "**228**",
    "With so much practice, he's probably the best in the world",
    "**229**",
    "Not too well",
    "231",
    "286",
    "**230**",
    "You have shoddy reasoning ",
    "**231**",
    "Oh no, how come?",
    "**232**",
    "Was it your fault",
    "**233**",
    "Life is about taking risks",
    "284",
    "**234**",
    "Ring in her glass of wine?",
    "**235**",
    "In search of the Holy Grail",
    "239",
    "267",
    "**236**",
    "The top of Mount Everest",
    "**237**",
    "Somewhere in Shanghai",
    "362",
    "**238**",
    "Why did they go there",
    "**239**",
    "Did they find it",
    "**240**",
    "Give me a sneak peek",
    "**241**",
    "But they look so cool",
    "**242**",
    "Pretty awesome so far",
    "250",
    "254",
    "**243**",
    "Someone really smart",
    "351",
    "**244**",
    "But life is about taking risks",
    "261",
    "**245**",
    "Is Tobias your favorite character?",
    "**246**",
    "He should have ended up with Nora",
    "**247**",
    "Was the algae island real",
    "279",
    "303",
    "**248**",
    "Can you bring me back some rocks",
    "**249**",
    "What's your favorite movie",
    "345",
    "**250**",
    "Cool! How so?",
    "**251**",
    "Reasoning with you is tough",
    "**252**",
    "Why there",
    "334",
    "**253**",
    "Broncos Super Bowl 2016",
    "395",
    "**254**",
    "Awesome, why?",
    "**255**",
    "Yeah, he is a smart guy",
    "**256**",
    "What was that guy thinking",
    "**257**",
    "His defense is average",
    "328",
    "370",
    "**258**",
    "I think my mixtape is more lit than yours",
    "350",
    "**259**",
    "I think some US Navy ships",
    "**260**",
    "Do you go hard in the paint",
    "331",
    "**261**",
    "But what if the risk doesn't pay off",
    "**262**",
    "Ben Roethlisberger is a giant",
    "327",
    "**263**",
    "Too bad Lincoln is on the most useless coin",
    "**264**",
    "I doubt that clumsy Jar Jar could destroy Luke",
    "**265**",
    "Aww why so bummed",
    "**266**",
    "Why did she break up with you",
    "**267**",
    "Wow did they find it",
    "**268**",
    "You should try to save them",
    "**269**",
    "Complete my bucket list",
    "277",
    "**270**",
    "What number was MJ",
    "**271**",
    "You could learn to fish",
    "318",
    "323",
    "355",
    "**272**",
    "To the tip of the Empire State Building",
    "**273**",
    "His dad was a good shooter",
    "**274**",
    "Her passionate soul",
    "333",
    "**275**",
    "Yeah, I think she's the one",
    "364",
    "**276**",
    "You could watch Heroes",
    "**277**",
    "What's on your bucket list",
    "278",
    "329",
    "**278**",
    "To build schools in areas of poverty",
    "390",
    "**279**",
    "I think it depends how you interpret the book",
    "**280**",
    "Many people sadly",
    "**281**",
    "Just ask the 2000 Baltimore Ravens!",
    "**282**",
    "Maybe they make you jump higher",
    "**283**",
    "I'm frightened to",
    "**284**",
    "What if the risk doesn't work though",
    "**285**",
    "Have you read 1984, too?",
    "**286**",
    "Aww why not",
    "**287**",
    "I believe in you",
    "337",
    "**288**",
    "You could make a case for Magic Johnson",
    "**289**",
    "What other shows do you like",
    "**290**",
    "What is Game of Thrones about",
    "291",
    "314",
    "**291**",
    "A whole bunch of people fight for control of the kingdom and basically all the cool characters die",
    "**292**",
    "What's got you down",
    "336",
    "**293**",
    "Was it your fault that she broke up with you",
    "365",
    "**294**",
    "I choose to believe the better story",
    "305",
    "**295**",
    "And he is amazing at ski ball!",
    "**296**",
    "Fill her house with a million roses",
    "352",
    "**297**",
    "Wouldn't teleporting be better",
    "339",
    "348",
    "**298**",
    "She is the most gorgeous wizard around",
    "356",
    "**299**",
    "I wish I was! I could wear awesome boots",
    "**300**",
    "Getting ready for my vacation",
    "**301**",
    "Piscine from Life of Pi had to be really mentally tough, too",
    "341",
    "**302**",
    "Learn to fish!",
    "**303**",
    "Does it matter as long as we learn from it?",
    "384",
    "**304**",
    "I believe the better story",
    "**305**",
    "Because we can learn more from it?",
    "**306**",
    "That book made me feel really bad for Boxer",
    "324",
    "**307**",
    "Only C-3PO is strong enough to destroy Luke Skywalker",
    "**308**",
    "Sebulba was just a big loser!",
    "335",
    "371",
    "**309**",
    "War sounds scary",
    "**310**",
    "Have you heard of Owen Meany",
    "**311**",
    "Just binge watching Netflix",
    "**312**",
    "Revive me Nikolai!",
    "**313**",
    "Darth Maul is super awesome",
    "317",
    "321",
    "**314**",
    "Basically all of your favorite characters dying",
    "**315**",
    "But at least he grows out of the Playbook",
    "**316**",
    "That guy is super clutch",
    "366",
    "**317**",
    "His light saber is my favorite",
    "**318**",
    "I would probably fall in the water",
    "385",
    "**319**",
    "The universe would come to an end as we know it",
    "389",
    "**320**",
    "Why so sad",
    "**321**",
    "His crazy flips are epic!",
    "**322**",
    "My mixtape is more fire than yours",
    "**323**",
    "I would probably fall into the water ",
    "**324**",
    "If only he was a little smarter!",
    "**325**",
    "Robin is an awesome character",
    "358",
    "**326**",
    "Never nude!!!",
    "**327**",
    "He could probably play defensive end",
    "**328**",
    "Scottie Pippen played great defense!",
    "**329**",
    "I want to make someone's wish come true",
    "**330**",
    "Neil Armstrong was the first man to step foot on the moon",
    "**331**",
    "I play like I'm 2001 Shaq",
    "376",
    "**332**",
    "What happens in Vegas, stays in Vegas",
    "**333**",
    "Is she also pretty",
    "**334**",
    "That place is awesome",
    "**335**",
    "Always bet on someone strong with the Force",
    "**336**",
    "I failed my test",
    "353",
    "**337**",
    "How can I get better at math",
    "**338**",
    "She is not to be trusted!",
    "360",
    "**339**",
    "Flying is definitely more fun than teleporting",
    "**340**",
    "The Lion King made me dislike hyenas",
    "**341**",
    "I can't believe he survived on that boat so long",
    "**342**",
    "What if I drop the ring",
    "**343**",
    "Because I said so",
    "**344**",
    "I also like 1984!",
    "**345**",
    "Avatar was super cool",
    "**346**",
    "It's going okay",
    "**347**",
    "You need to man up!",
    "**348**",
    "No way, flying is more fun",
    "372",
    "**349**",
    "Yoda is super wise and strong",
    "**350**",
    "No way, mine has a Drake feature",
    "**351**",
    "Albert Einstein was super smart!",
    "383",
    "**352**",
    "Uhhh that sounds like an expensive proposal",
    "**353**",
    "I guess you need to study more",
    "368",
    "**354**",
    "I wish I could read her mind",
    "359",
    "402",
    "**355**",
    "Fishing is boring",
    "**356**",
    "Selena Gomez was also a cute wizard",
    "**357**",
    "I really like A Prayer for Owen Meany",
    "363",
    "**358**",
    "It's scary how she always carries a gun",
    "**359**",
    "Reading minds might not be the best power to have",
    "377",
    "**360**",
    "Never trust a girl who didn't watch the Powerpuff Girls",
    "**361**",
    "I'm doing fine",
    "381",
    "**362**",
    "Doesn't Shanghai have super cool buildings",
    "**363**",
    "Owen Meany is hilarious!",
    "398",
    "**364**",
    "How are you going to propose",
    "**365**",
    "I forgot about our anniversary",
    "**366**",
    "Aaron Rodgers is super clutch!",
    "**367**",
    "Don't let her go! It is destined to be!",
    "**368**",
    "I need to figure out a fun way to do it",
    "396",
    "**369**",
    "Around Christmas time",
    "**370**",
    "The 1985 Bears had great defense",
    "**371**",
    "Aliens creep me out",
    "**372**",
    "Why is flying more fun",
    "397",
    "**373**",
    "My pet died",
    "379",
    "392",
    "**374**",
    "I wish I was a famous basketball player",
    "**375**",
    "It was designed by Apple in California",
    "**376**",
    "Didn't he always fight with Kobe",
    "**377**",
    "Why would reading minds not be awesome",
    "**378**",
    "My parents grounded me",
    "**379**",
    "What kind of pet was it",
    "**380**",
    "I'm awesome, I could pull anything off",
    "**381**",
    "You should go out and do something epic!",
    "**382**",
    "Do you go to a tough school",
    "**383**",
    "He correctly predicted gravitational waves!",
    "**384**",
    "I guess you are right",
    "400",
    "**385**",
    "Do you know how to swim",
    "**386**",
    "Qui-Gon Jinn was played by Liam Neeson!",
    "**387**",
    "Why do you want to fly",
    "**388**",
    "What else do you like about her",
    "**389**",
    "That's scary to think about, let's just enjoy life while we can",
    "**390**",
    "That's great! Spreading education is an awesome goal",
    "**391**",
    "My friend is mad at me",
    "**392**",
    "Aww what kind of pet was it",
    "**393**",
    "Bill Russel won eleven championships!",
    "**394**",
    "I don't have a favorite president ",
    "**395**",
    "I can't believe they won with so little offense",
    "**396**",
    "Studying with friends is fun",
    "**397**",
    "You could pick up a lot of girls if you could fly",
    "**398**",
    "Owen's voice is so annoying, but I love it",
    "**399**",
    "It was the first race Anakin ever completed",
    "**400**",
    "I'm always right",
    "**401**",
    "Prospero is my favorite wizard of all time",
    "**402**",
    "Be careful what you wish for",
    "404",
    "**403**",
    "I wish I could go to Hogwarts",
    "**404**",
    "I wish I had fairy godparents to grant all my wishes",
]