//
//  preTraining.swift
//  BuddyBotFinal
//
//  Created by Mateo Correa on 12/9/15.
//  Copyright © 2015 Mateo Correa. All rights reserved.
//

import Foundation


var predRecordedConvos = [
    "Hello", "Howdy", "Do you like Harry Potter?", "I love Emma Watson", "Are you a wizard?", "No, i have no magical powers", "Do you like Star Wars?", "yes, everybody loves starwars", "but i hate jar jar", "who doesnt hate jar jar", "Who has won the most Superbowls?", "the steelers", "Who is the best shooter in the NBA?", "steph curry", "Who is the greatest basketball player of all time?", "Michael Jordan", "Do you like 'How I Met Your Mother?", "Yes, I love that show!", "Is Ted your favorite character?", "No way, Barney is Legen... wait for it... dary!", "What television shows do you like?", "The Walking Dead is one of my favorites.", "Do you read books often?", "Yeah! A book a day keeps the engineer away!", "Who is your favorite president?", "Lincoln was a tough guy!"
]

var preRecordedConvos = [
    "**1**",
    "Hello",
    "2",
    "27",
    "38",
    "59",
    "**2**",
    "Howdy",
    "28",
    "31",
    "**3**",
    "Do you like Harry Potter?",
    "4",
    "**4**",
    "I love Emma Watson",
    "38",
    "42",
    "**5**",
    "Are you a wizard?",
    "6",
    "**6**",
    "No, i have no magical powers",
    "29",
    "49",
    "51",
    "55",
    "56",
    "**7**",
    "Do you like Star Wars?",
    "8",
    "**8**",
    "yes, everybody loves starwars",
    "32",
    "43",
    "47",
    "**9**",
    "but i hate jar jar",
    "10",
    "**10**",
    "who doesnt hate jar jar",
    "30",
    "48",
    "62",
    "**11**",
    "Who has won the most Superbowls?",
    "12",
    "**12**",
    "the steelers",
    "**13**",
    "Who is the best shooter in the NBA?",
    "14",
    "**14**",
    "steph curry",
    "54",
    "**15**",
    "Who is the greatest basketball player of all time?",
    "16",
    "**16**",
    "Michael Jordan",
    "33",
    "**17**",
    "Do you like 'How I Met Your Mother?",
    "18",
    "**18**",
    "Yes, I love that show!",
    "**19**",
    "Is Ted your favorite character?",
    "20",
    "**20**",
    "No way, Barney is Legen... wait for it... dary!",
    "58",
    "**21**",
    "What television shows do you like?",
    "22",
    "**22**",
    "The Walking Dead is one of my favorites.",
    "63",
    "**23**",
    "Do you read books often?",
    "24",
    "**24**",
    "Yeah! A book a day keeps the engineer away!",
    "44",
    "45",
    "**25**",
    "Who is your favorite president?",
    "26",
    "**26**",
    "Lincoln was a tough guy!",
    "36",
    "37",
    "**27**",
    "sup bro",
    "**28**",
    "lol are you a cowboy",
    "**29**",
    "what happened to them",
    "50",
    "**30**",
    "I think only George Lucas likes him",
    "34",
    "**31**",
    "Hello Mr. Southern Man",
    "**32**",
    "never date a girl unless she likes star wars",
    "**33**",
    "he is a great basketball player",
    "35",
    "39",
    "41",
    "**34**",
    "Michael jordan",
    "46",
    "53",
    "61",
    "**35**",
    "he even has nice shoes",
    "**36**",
    "was he your favorite president",
    "**37**",
    "what made him so tough",
    "**38**",
    "sup man",
    "40",
    "**39**",
    "So was Magic Johnson!",
    "**40**",
    "Nothing much, you?",
    "52",
    "57",
    "60",
    "**41**",
    "I think LeBron might be better",
    "**42**",
    "What do you love about her",
    "**43**",
    "I don't trust people who don't",
    "**44**",
    "What books do you read",
    "**45**",
    "What is your favorite book to read?",
    "**46**",
    "Do you like his shoe brand?",
    "**47**",
    "unless they have no brain",
    "**48**",
    "George Lucas, obviously",
    "**49**",
    "Why don't you have magical powers?",
    "**50**",
    "They got lost bro",
    "**51**",
    "Why don't you?",
    "**52**",
    "I've been doing a lot of homework",
    "**53**",
    "He is the greatest competitor of all time",
    "**54**",
    "He can shoot!",
    "**55**",
    "Where did they go",
    "**56**",
    "Why not",
    "**57**",
    "Mostly Netflix and chilling",
    "**58**",
    "But Marshall cares about the environment!",
    "**59**",
    "How's it going?",
    "**60**",
    "I'm just hanging out listening to music",
    "**61**",
    "I bet I could 1v1 him",
    "**62**",
    "Exactly! Even Qui-Gon got annoyed",
    "**63**",
    "AHHHH ZOMBIES!!!",
]
